name: Build and Run

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build
      run: dotnet build

    - name: Run Application
      run: |
        cd /root/LSF_Backend/bin/Debug/net8.0/
        dotnet LSF.dll
